version: '3'

services:
  trade-simulator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trade-simulator
    volumes:
      - ./data:/app/data
    ports:
      - "8080:8080"
    environment:
      - EXCHANGE=OKX
      - SYMBOL=BTC-USDT-SWAP
      - ORDER_TYPE=market
      - QUANTITY=1.0
      - VOLATILITY=0.02
      - TIER=1
    # Override the default command if needed
    # command: ["--exchange=${EXCHANGE}", "--symbol=${SYMBOL}", "--order-type=${ORDER_TYPE}", "--quantity=${QUANTITY}", "--volatility=${VOLATILITY}", "--tier=${TIER}"]

  # Add a container for development environment (with all dependencies installed but without building)
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: trade-simulator-dev
    volumes:
      - .:/app
    command: /bin/bash
    stdin_open: true
    tty: true 